/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Blockchain_CONSTANTS_H
#define Blockchain_CONSTANTS_H

#include "Blockchain_types.h"



class BlockchainConstants {
 public:
  BlockchainConstants();

};

extern const BlockchainConstants g_Blockchain_constants;



#endif
