/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Miner_CONSTANTS_H
#define Miner_CONSTANTS_H

#include "Miner_types.h"



class MinerConstants {
 public:
  MinerConstants();

};

extern const MinerConstants g_Miner_constants;



#endif
