/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Miner_constants.h"



const MinerConstants g_Miner_constants;

MinerConstants::MinerConstants() {
}



