/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Transaction_constants.h"



const TransactionConstants g_Transaction_constants;

TransactionConstants::TransactionConstants() {
}



