/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Transaction_CONSTANTS_H
#define Transaction_CONSTANTS_H

#include "Transaction_types.h"



class TransactionConstants {
 public:
  TransactionConstants();

};

extern const TransactionConstants g_Transaction_constants;



#endif
